# Generated by Django 2.1.4 on 2020-05-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='网站信息')),
                ('img', models.CharField(blank=True, max_length=128, null=True, verbose_name='网页配图')),
                ('url', models.CharField(max_length=256, verbose_name='网页地址')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='网页来源')),
                ('visiting', models.PositiveIntegerField(default=0, verbose_name='网页访问量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
