# Generated by Django 2.1.4 on 2020-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_auto_20200520_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.CharField(max_length=128, null=True, verbose_name='网站配图'),
        ),
    ]
