# Generated by Django 2.1.4 on 2020-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_remove_entry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTR_Implied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceptno', models.CharField(max_length=128, verbose_name='受理号')),
                ('Drugname', models.CharField(max_length=128, verbose_name='药品名称')),
                ('Corpname', models.CharField(max_length=128, verbose_name='申请人名称')),
                ('Indication', models.CharField(max_length=128, verbose_name='适应症')),
                ('Register_Type', models.CharField(max_length=128, verbose_name='注册分类')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Uptime', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
    ]
