# Generated by Django 2.1.4 on 2020-05-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_ctr_implied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CTR_Implied',
            new_name='CtrImplied',
        ),
    ]
